# Generated by Django 4.1.6 on 2023-02-04 23:07

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnies',
            name='image_link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='compagnies',
            name='market_cap',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='CompaniesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=250)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compagnies')),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieIncomeStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('full_annual_income_statement', picklefield.fields.PickledObjectField(editable=False)),
                ('full_quarterly_income_statement', picklefield.fields.PickledObjectField(editable=False)),
                ('light_annual_income_statement', picklefield.fields.PickledObjectField(editable=False)),
                ('light_quarterly_income_statement', picklefield.fields.PickledObjectField(editable=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compagnies')),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieCashFlowStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('full_annual_cash_flow_statement', picklefield.fields.PickledObjectField(editable=False)),
                ('full_quarterly_cash_flow_statement', picklefield.fields.PickledObjectField(editable=False)),
                ('light_annual_cash_flow_statement', picklefield.fields.PickledObjectField(editable=False)),
                ('light_quarterly_cash_flow_statement', picklefield.fields.PickledObjectField(editable=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compagnies')),
            ],
        ),
        migrations.CreateModel(
            name='CompagnieBalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('full_annual_balance_sheet', picklefield.fields.PickledObjectField(editable=False)),
                ('full_quarterly_balance_sheet', picklefield.fields.PickledObjectField(editable=False)),
                ('light_annual_balance_sheet', picklefield.fields.PickledObjectField(editable=False)),
                ('light_quarterly_balance_sheet', picklefield.fields.PickledObjectField(editable=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.compagnies')),
            ],
        ),
    ]
