# Generated by Django 4.1.6 on 2023-02-04 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_compagnies_image_link_compagnies_market_cap_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompagnieIncomeStatement',
            new_name='CompanieBalanceSheet',
        ),
        migrations.RenameModel(
            old_name='CompagnieBalanceSheet',
            new_name='CompanieCashFlowStatement',
        ),
        migrations.RenameModel(
            old_name='CompagnieCashFlowStatement',
            new_name='CompanieIncomeStatement',
        ),
        migrations.RenameModel(
            old_name='Compagnies',
            new_name='Companies',
        ),
        migrations.RenameField(
            model_name='companiebalancesheet',
            old_name='full_annual_income_statement',
            new_name='full_annual_balance_sheet',
        ),
        migrations.RenameField(
            model_name='companiebalancesheet',
            old_name='full_quarterly_income_statement',
            new_name='full_quarterly_balance_sheet',
        ),
        migrations.RenameField(
            model_name='companiebalancesheet',
            old_name='light_annual_income_statement',
            new_name='light_annual_balance_sheet',
        ),
        migrations.RenameField(
            model_name='companiebalancesheet',
            old_name='light_quarterly_income_statement',
            new_name='light_quarterly_balance_sheet',
        ),
        migrations.RenameField(
            model_name='companiecashflowstatement',
            old_name='full_annual_balance_sheet',
            new_name='full_annual_cash_flow_statement',
        ),
        migrations.RenameField(
            model_name='companiecashflowstatement',
            old_name='full_quarterly_balance_sheet',
            new_name='full_quarterly_cash_flow_statement',
        ),
        migrations.RenameField(
            model_name='companiecashflowstatement',
            old_name='light_annual_balance_sheet',
            new_name='light_annual_cash_flow_statement',
        ),
        migrations.RenameField(
            model_name='companiecashflowstatement',
            old_name='light_quarterly_balance_sheet',
            new_name='light_quarterly_cash_flow_statement',
        ),
        migrations.RenameField(
            model_name='companieincomestatement',
            old_name='full_annual_cash_flow_statement',
            new_name='full_annual_income_statement',
        ),
        migrations.RenameField(
            model_name='companieincomestatement',
            old_name='full_quarterly_cash_flow_statement',
            new_name='full_quarterly_income_statement',
        ),
        migrations.RenameField(
            model_name='companieincomestatement',
            old_name='light_annual_cash_flow_statement',
            new_name='light_annual_income_statement',
        ),
        migrations.RenameField(
            model_name='companieincomestatement',
            old_name='light_quarterly_cash_flow_statement',
            new_name='light_quarterly_income_statement',
        ),
    ]
