# Generated by Django 4.1.6 on 2023-02-04 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_compagnieincomestatement_companiebalancesheet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='created_at',
            new_name='created_at_date',
        ),
    ]
