# Generated by Django 4.1.6 on 2023-02-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_created_at_companies_created_at_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Companie',
        ),
        migrations.RenameModel(
            old_name='CompaniesInfo',
            new_name='CompanieInfo',
        ),
    ]
