# Generated by Django 4.1.6 on 2023-02-05 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_companies_companie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanieCashFlowStatement',
            new_name='CompanieCashFlow',
        ),
    ]
