# Generated by Django 4.1.6 on 2023-02-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_companiecashflowstatement_companiecashflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companiecashflow',
            old_name='full_annual_cash_flow_statement',
            new_name='full_annual_cash_flow',
        ),
        migrations.RenameField(
            model_name='companiecashflow',
            old_name='full_quarterly_cash_flow_statement',
            new_name='full_quarterly_cash_flow',
        ),
        migrations.RenameField(
            model_name='companiecashflow',
            old_name='light_annual_cash_flow_statement',
            new_name='light_annual_cash_flow',
        ),
        migrations.RenameField(
            model_name='companiecashflow',
            old_name='light_quarterly_cash_flow_statement',
            new_name='light_quarterly_cash_flow',
        ),
    ]
