# Generated by Django 4.1.6 on 2023-02-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_companie_ticker_alter_companieinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='companiecashflow',
            name='full_num_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companiecashflow',
            name='full_num_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companiecashflow',
            name='light_num_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companiecashflow',
            name='light_num_row',
            field=models.IntegerField(default=0),
        ),
    ]
