# Generated by Django 4.1.6 on 2023-02-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_companiecashflow_full_num_col_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companieincomestatement',
            name='full_num_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companieincomestatement',
            name='full_num_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companieincomestatement',
            name='light_num_col',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companieincomestatement',
            name='light_num_row',
            field=models.IntegerField(default=0),
        ),
    ]
