# Generated by Django 4.1.6 on 2023-02-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_companieinfo_next_earnings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiebalancesheet',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.companie'),
        ),
        migrations.AlterField(
            model_name='companiebalancesheet',
            name='ticker',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='companiecashflow',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.companie'),
        ),
        migrations.AlterField(
            model_name='companiecashflow',
            name='ticker',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='companieincomestatement',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.companie'),
        ),
        migrations.AlterField(
            model_name='companieincomestatement',
            name='ticker',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='companieinfo',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compagnie_info', to='api.companie'),
        ),
        migrations.AlterField(
            model_name='companieinfo',
            name='ticker',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
