# Generated by Django 4.1.6 on 2023-02-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_companiebalancesheet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='ticker',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
