# Generated by Django 4.1.7 on 2023-02-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_companie_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
