# Generated by Django 4.1.7 on 2023-02-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='companie',
            name='share_price',
            field=models.FloatField(default=0),
        ),
    ]
