# Generated by Django 4.1.7 on 2023-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_dailyupdatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyupdatestatus',
            name='last_updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
